package dev.zonary123.zshop.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import dev.zonary123.zshop.models.DataButtonProduct;
import dev.zonary123.zshop.models.Product;
import dev.zonary123.zshop.models.Shop;
import dev.zonary123.zutils.api.EconomyApi;
import dev.zonary123.zutils.models.EconomySelector;
import dev.zonary123.zutils.utils.UtilsFile;

import javax.annotation.Nonnull;
import java.util.UUID;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
public class ProductIndexGui extends InteractiveCustomUIPage<ProductIndexGui.BindingData> {
  private final Shop shop;

  public ProductIndexGui(@Nonnull PlayerRef playerRef, @Nonnull CustomPageLifetime lifetime, Shop shop) {
    super(playerRef, lifetime, BindingData.CODEC);
    this.shop = shop;
  }


  public static class BindingData {
    static final String KEY_DATA = "Data";
    public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)
      .addField(new KeyedCodec<>(KEY_DATA, Codec.STRING), (searchGuiData, s) -> searchGuiData.data = s,
        searchGuiData -> searchGuiData.data)
      .build();

    private String data;

    public DataButtonProduct getData() {
      return UtilsFile.getGson().fromJson(this.data, DataButtonProduct.class);
    }

  }

  @Override
  public void build(
    @Nonnull Ref<EntityStore> ref,
    @Nonnull UICommandBuilder uiCommandBuilder,
    @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {
    uiCommandBuilder.append("Pages/ProductsIndex.ui");
    int rowIndex = 0;
    int cardsInCurrentRow = 0;
    for (Product product : shop.getProducts()) {
      if (cardsInCurrentRow == 0) {
        uiCommandBuilder.appendInline("#IndexCards", "Group { LayoutMode: Left; Anchor: (Bottom: 0); }");
      }

      uiCommandBuilder.append("#IndexCards[" + rowIndex + "]", "Pages/ProductEntry.ui");

      uiCommandBuilder.set("#IndexCards[" + rowIndex + "][" + cardsInCurrentRow + "] #IndexIcon.ItemId",
        product.getProduct());
      uiCommandBuilder.set("#IndexCards[" + rowIndex + "][" + cardsInCurrentRow + "] #IndexBuyPrice.Text",
        "Buy: " + product.getBuyPrice().toString()
      );
      uiCommandBuilder.set("#IndexCards[" + rowIndex + "][" + cardsInCurrentRow + "] #IndexSellPrice.Text",
        "Sell: " + product.getSellPrice().toString());

      uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating,
        "#IndexCards[" + rowIndex + "][" + cardsInCurrentRow + "]", EventData.of(BindingData.KEY_DATA, UtilsFile.getGson().toJson(
          DataButtonProduct.builder()
            .product(product)
            .economy(shop.getEconomy())
            .build(
            )))
      );

      ++cardsInCurrentRow;
      if (cardsInCurrentRow >= 4) {
        cardsInCurrentRow = 0;
        ++rowIndex;
      }
    }
  }

  @Override
  public void handleDataEvent(
    @Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @Nonnull BindingData data) {
    super.handleDataEvent(ref, store, data);
    boolean changed = false;
    DataButtonProduct buttonData = data.getData();
    if (buttonData != null) {
      var player = store.getComponent(ref, Player.getComponentType());
      if (player == null) return;
      Product product = buttonData.getProduct();
      EconomySelector economy = buttonData.getEconomy();
      UUID playerUuid = playerRef.getUuid();
      if (!EconomyApi.hasBalance(playerUuid, economy, product.getBuyPrice())) {
        this.playerRef.sendMessage(Message.raw("You do not have enough balance to buy this product."));
        return;
      }
      changed = true;
      if (EconomyApi.withdraw(playerUuid, economy, product.getBuyPrice(), "Shop purchase: " + product.getProduct())) {
        this.playerRef.sendMessage(Message.raw("You have purchased the product for " + product.getBuyPrice().toString() + "."));
        ItemStack itemStack = new ItemStack(product.getProduct());
        if (!player.getInventory().getHotbar().addItemStack(itemStack).succeeded() && !player.getInventory().getStorage().addItemStack(itemStack).succeeded()) {
          return;
        }
      } else {
        this.playerRef.sendMessage(Message.raw("An error occurred while processing your purchase."));
      }
    }
    if (changed) {
      this.playerRef.sendMessage(Message.raw("Changes processed."));
    }
  }

}
