package dev.zonary123.zshop.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.inventory.ItemStack;
import com.hypixel.hytale.server.core.inventory.transaction.ItemStackTransaction;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import dev.zonary123.zshop.ZShop;
import dev.zonary123.zshop.models.DataButtonProduct;
import dev.zonary123.zshop.models.Product;
import dev.zonary123.zshop.models.Shop;
import dev.zonary123.zutils.api.EconomyApi;
import dev.zonary123.zutils.models.EconomySelector;
import dev.zonary123.zutils.utils.FormatMessage;
import dev.zonary123.zutils.utils.UtilsFile;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import javax.annotation.Nonnull;
import java.math.BigDecimal;
import java.util.UUID;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
@Getter
@Setter
public class ProductIndexGui extends InteractiveCustomUIPage<ProductIndexGui.BindingData> {
  private final Shop shop;
  private int amount;

  public ProductIndexGui(@Nonnull PlayerRef playerRef, @Nonnull CustomPageLifetime lifetime, Shop shop) {
    super(playerRef, lifetime, BindingData.CODEC);
    this.shop = shop;
  }


  @Data
  public static class BindingData {
    static final String KEY_DATA = "Data";
    static final String KEY_INPUT_FIELD = "@InputField";

    public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)
      .addField(new KeyedCodec<>(KEY_DATA, Codec.STRING), (searchGuiData, s) -> searchGuiData.data = s,
        searchGuiData -> searchGuiData.data)
      .addField(new KeyedCodec<>(KEY_INPUT_FIELD, Codec.INTEGER), (searchGuiData, i) -> searchGuiData.amount = i,
        searchGuiData -> searchGuiData.amount)
      .build();

    private String data;
    private Integer amount;

    public DataButtonProduct getData() {
      return UtilsFile.getGson().fromJson(this.data, DataButtonProduct.class);
    }

  }

  @Override
  public void build(
    @Nonnull Ref<EntityStore> ref,
    @Nonnull UICommandBuilder uiCommandBuilder,
    @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {
    uiCommandBuilder.append("Pages/ProductsIndex.ui");

    var lang = ZShop.get().getLang();
    uiCommandBuilder.set("#TitleProducts.Text", lang.getTitleProducts()
      .replace("%shop%", shop.getName()));

    this.buildProductList(uiCommandBuilder, uiEventBuilder);
  }

  private void buildProductList(
    @Nonnull UICommandBuilder uiCommandBuilder,
    @Nonnull UIEventBuilder uiEventBuilder) {
    var lang = ZShop.get().getLang();
    int rowIndex = 0;
    int cardsInCurrentRow = 0;
    for (Product product : shop.getProducts()) {

      if (cardsInCurrentRow == 0) {
        uiCommandBuilder.appendInline("#IndexCards", "Group { LayoutMode: Left; Anchor: (Bottom: 0); }");
      }
      String indexCardSelector = "#IndexCards[" + rowIndex + "]";

      uiCommandBuilder.append(indexCardSelector, "Pages/ProductEntry.ui");

      String cardSelector = indexCardSelector + "[" + cardsInCurrentRow + "]";
      uiCommandBuilder.set(cardSelector + " #IndexIcon.ItemId",
        product.getProduct());
      uiCommandBuilder.set(cardSelector + " #IndexBuyPrice.Text",
        lang.getBuyPrice()
          .replace("%price%", product.getBuyPrice().toString())
      );
      uiCommandBuilder.set(cardSelector + " #IndexSellPrice.Text",
        lang.getSellPrice()
          .replace("%price%", product.getSellPrice().toString())
      );


      // Buy Button Binding
      uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating,
        cardSelector + " #BuyButton", EventData.of(BindingData.KEY_DATA,
          UtilsFile.getGson().toJson(
            DataButtonProduct.builder()
              .product(product)
              .economy(shop.getEconomy())
              .action(ProductAction.BUY)
              .build(
              )))
      );
      // Sell Button Binding
      uiEventBuilder.addEventBinding(
        CustomUIEventBindingType.Activating,
        cardSelector + " #SellButton", EventData.of(BindingData.KEY_DATA,
          UtilsFile.getGson().toJson(
            DataButtonProduct.builder()
              .product(product)
              .economy(shop.getEconomy())
              .action(ProductAction.SELL)
              .build(
              )))
      );
      // Input amount
      String selectorInputField = cardSelector + " #AmountField";
      uiEventBuilder.addEventBinding(
        CustomUIEventBindingType.ValueChanged,
        selectorInputField,
        EventData.of(BindingData.KEY_INPUT_FIELD, "#AmountField.Value"),
        false
      );


      ++cardsInCurrentRow;
      if (cardsInCurrentRow >= 4) {
        cardsInCurrentRow = 0;
        ++rowIndex;
      }
    }
  }

  @Override
  public void handleDataEvent(
    @Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @Nonnull BindingData data) {
    super.handleDataEvent(ref, store, data);
    DataButtonProduct buttonData = data.getData();
    if (data.amount != null) {
      this.amount = data.amount;
      var commandBuilder = new UICommandBuilder();
      var eventBuilder = new UIEventBuilder();
      updateCard(ref, store, buttonData, commandBuilder, eventBuilder);
      return;
    }

    if (buttonData != null) {
      if (amount <= 0) amount = 1;
      var player = store.getComponent(ref, Player.getComponentType());
      if (player == null) return;

      switch (buttonData.getAction()) {
        case BUY -> {
          buy(buttonData, this.playerRef, player, amount);
        }
        case SELL -> {
          sell(buttonData, this.playerRef, player, amount);
        }
        default -> {
          player.sendMessage(
            Message.raw("Unknown action: " + buttonData.getAction().toString())
          );
        }
      }
      var commandBuilder = new UICommandBuilder();
      var eventBuilder = new UIEventBuilder();
      this.sendUpdate(commandBuilder, eventBuilder, false);
      //this.build(ref, commandBuilder, eventBuilder, store);
    }
  }

  private void updateCard(Ref<EntityStore> ref, Store<EntityStore> store, DataButtonProduct buttonData, UICommandBuilder commandBuilder, UIEventBuilder eventBuilder) {

  }

  private void buy(DataButtonProduct data, PlayerRef playerRef, Player player, int amount) {
    Product product = data.getProduct();
    EconomySelector economy = data.getEconomy();
    UUID playerUuid = playerRef.getUuid();
    BigDecimal price = product.getBuyPrice().multiply(BigDecimal.valueOf(amount));
    if (!EconomyApi.hasBalance(playerUuid, economy, price)) {
      playerRef.sendMessage(
        FormatMessage.formatMessage(
          ZShop.get().getLang().getPurchaseFailFunds()
            .replace("%amount%", String.valueOf(amount))
            .replace("%product%", product.getProduct())
            .replace("%total_price%", price.toString())
        )
      );
      return;
    }
    ItemStack itemStack = new ItemStack(product.getProduct(), amount);
    String itemId = itemStack.getItem().getId();
    ItemStackTransaction transaction = player.getInventory().getCombinedHotbarFirst().addItemStack(
      itemStack
    );
    ItemStack remainder = transaction.getRemainder();
    if (remainder != null && !remainder.isEmpty()) {
      playerRef.sendMessage(
        FormatMessage.formatMessage(
          ZShop.get().getLang().getPurchaseFailSpace()
            .replace("%amount%", String.valueOf(amount))
            .replace("%product%", itemId)
        )
      );
      return;
    }
    String reason = ZShop.get().getLang().getPurchaseReason()
      .replace("%amount%", String.valueOf(amount))
      .replace("%product%", itemId);
    if (EconomyApi.withdraw(playerUuid, economy, price, reason)) {
      playerRef.sendMessage(
        FormatMessage.formatMessage(
          ZShop.get().getLang().getPurchaseSuccess()
            .replace("%amount%", String.valueOf(amount))
            .replace("%product%", itemId)
            .replace("%total_price%", price.toString())
        )
      );
    }
  }

  private void sell(DataButtonProduct data, PlayerRef playerRef, Player player, int amount) {

  }
}
