package dev.zonary123.zshop.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import dev.zonary123.zshop.configs.Shops;
import dev.zonary123.zshop.models.Shop;

import javax.annotation.Nonnull;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
public class ShopsIndexGui extends InteractiveCustomUIPage<ShopsIndexGui.BindingData> {

  public ShopsIndexGui(@Nonnull PlayerRef playerRef, @Nonnull CustomPageLifetime lifetime) {
    super(playerRef, lifetime, BindingData.CODEC);
  }


  public static class BindingData {
    static final String KEY_BUTTON = "Button";

    public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)
      .addField(new KeyedCodec<>(KEY_BUTTON, Codec.STRING), (searchGuiData, s) -> searchGuiData.button = s, searchGuiData -> searchGuiData.button)
      .build();

    private String button;

  }

  @Override
  public void build(
    @Nonnull Ref<EntityStore> ref,
    @Nonnull UICommandBuilder uiCommandBuilder,
    @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {
    uiCommandBuilder.append("Pages/ShopsIndex.ui");
    var shops = Shops.SHOPS;
    int rowIndex = 0;
    int cardsInCurrentRow = 0;
    for (Shop shop : shops) {
      if (cardsInCurrentRow == 0) {
        uiCommandBuilder.appendInline("#IndexCards", "Group { LayoutMode: Left; Anchor: (Bottom: 0); }");
      }

      uiCommandBuilder.append("#IndexCards[" + rowIndex + "]", "Pages/ShopEntry.ui");

      uiCommandBuilder.set("#IndexCards[" + rowIndex + "][" + cardsInCurrentRow + "] #IndexIcon.ItemId",
        shop.getIcon());
      uiCommandBuilder.set("#IndexCards[" + rowIndex + "][" + cardsInCurrentRow + "] #IndexTitle.Text",
        shop.getTitle());
      uiCommandBuilder.set("#IndexCards[" + rowIndex + "][" + cardsInCurrentRow + "] #IndexDescription.Text",
        shop.getDescription());
      uiEventBuilder.addEventBinding(CustomUIEventBindingType.Activating,
        "#IndexCards[" + rowIndex + "][" + cardsInCurrentRow + "]", EventData.of("Button", shop.getId()));

      ++cardsInCurrentRow;
      if (cardsInCurrentRow >= 3) {
        cardsInCurrentRow = 0;
        ++rowIndex;
      }
    }
  }

  @Override
  public void handleDataEvent(
    @Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @Nonnull BindingData data) {
    super.handleDataEvent(ref, store, data);
    boolean changed = false;
    if (data.button != null) {
      var shop = Shops.getShopById(data.button);
      var playerRef = store.getComponent(ref, PlayerRef.getComponentType());
      var player = store.getComponent(ref, Player.getComponentType());
      if (shop == null || player == null || playerRef == null) return;
      player.getPageManager().openCustomPage(
        ref,
        store,
        new ProductIndexGui(playerRef, CustomPageLifetime.CanDismiss, shop)
      );
    }
    if (changed) {
      this.playerRef.sendMessage(Message.raw("Changes processed."));
    }
  }

}
