package dev.zonary123.zshop.ui;

import com.hypixel.hytale.codec.Codec;
import com.hypixel.hytale.codec.KeyedCodec;
import com.hypixel.hytale.codec.builder.BuilderCodec;
import com.hypixel.hytale.component.ComponentAccessor;
import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
import com.hypixel.hytale.protocol.packets.interface_.CustomUIEventBindingType;
import com.hypixel.hytale.server.core.Message;
import com.hypixel.hytale.server.core.asset.type.item.config.Item;
import com.hypixel.hytale.server.core.command.system.MatchResult;
import com.hypixel.hytale.server.core.entity.entities.Player;
import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
import com.hypixel.hytale.server.core.modules.i18n.I18nModule;
import com.hypixel.hytale.server.core.ui.builder.EventData;
import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
import dev.zonary123.zshop.ZShop;
import dev.zonary123.zshop.models.Product;
import dev.zonary123.zshop.models.Shop;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;

import javax.annotation.Nonnull;
import java.math.BigDecimal;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

// Generated by Hytale UI Builder (https://hytale.ellie.au).
// You may edit this class as necessary, or copy parts only.
public class ShopEditIndexGui extends InteractiveCustomUIPage<ShopEditIndexGui.SearchGuiData> {
  private Shop shop;
  private String searchQuery = "";
  private final Map<String, Item> visibleItems = new HashMap<>();

  public ShopEditIndexGui(@Nonnull PlayerRef playerRef, @Nonnull CustomPageLifetime lifetime, Shop shop) {
    super(playerRef, lifetime, SearchGuiData.CODEC);
    this.shop = shop;
  }


  public static class SearchGuiData {
    static final String KEY_ITEM = "Item";
    static final String KEY_SEARCH_QUERY = "@SearchQuery";
    public static final BuilderCodec<SearchGuiData> CODEC = BuilderCodec.<SearchGuiData>builder(SearchGuiData.class, SearchGuiData::new)
      .addField(new KeyedCodec<>(KEY_SEARCH_QUERY, Codec.STRING), (searchGuiData, s) -> searchGuiData.searchQuery = s, searchGuiData -> searchGuiData.searchQuery)
      .addField(new KeyedCodec<>(KEY_ITEM, Codec.STRING), (searchGuiData, s) -> searchGuiData.item = s, searchGuiData -> searchGuiData.item).build();

    private String item;
    private String searchQuery;

  }

  @Override
  public void build(
    @Nonnull Ref<EntityStore> ref,
    @Nonnull UICommandBuilder uiCommandBuilder,
    @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {
    uiCommandBuilder.append("Pages/ItemsIndex.ui");
    uiCommandBuilder.set("#SearchInput.Value", this.searchQuery);
    uiEventBuilder.addEventBinding(CustomUIEventBindingType.ValueChanged, "#SearchInput", EventData.of("@SearchQuery", "#SearchInput.Value"), false);
    this.buildList(ref, uiCommandBuilder, uiEventBuilder, store);
  }

  private void buildList(
    @Nonnull Ref<EntityStore> ref,
    @Nonnull UICommandBuilder commandBuilder,
    @Nonnull UIEventBuilder eventBuilder, @Nonnull ComponentAccessor<EntityStore> componentAccessor) {
    HashMap<String, Item> itemList = new HashMap<>(ZShop.ITEMS);
    Player playerComponent = componentAccessor.getComponent(ref, Player.getComponentType());

    assert playerComponent != null;

    if (this.searchQuery.isEmpty()) {
      this.visibleItems.clear();
      this.visibleItems.putAll(itemList);
      //Collections.sort(this.visibleCommands);
    } else {
      ObjectArrayList<SearchResult> results = new ObjectArrayList<>();

      for (Map.Entry<String, Item> entry : itemList.entrySet()) {
        if (entry.getValue() != null) {
          results.add(new SearchResult(entry.getKey(), MatchResult.EXACT));
        }
      }

      String[] terms = this.searchQuery.split(" ");

      for (String s : terms) {
        String term = s.toLowerCase(Locale.ENGLISH);

        for (int cmdIndex = results.size() - 1; cmdIndex >= 0; --cmdIndex) {
          SearchResult result = results.get(cmdIndex);
          Item item = itemList.get(result.name);
          MatchResult match = MatchResult.NONE;
          if (item != null) {
            var message = I18nModule.get().getMessage(this.playerRef.getLanguage(), item.getTranslationKey());
            match = message != null && message.toLowerCase(Locale.ENGLISH).contains(term) ? MatchResult.EXACT : MatchResult.NONE;
          }

          if (match == MatchResult.NONE) {
            results.remove(cmdIndex);
          } else {
            result.match = result.match.min(match);
          }
        }
      }

      results.sort(SearchResult.COMPARATOR);
      this.visibleItems.clear();

      for (SearchResult result : results) {
        this.visibleItems.put(result.name, itemList.get(result.name));
      }
    }
    this.buildButtons(this.visibleItems, playerComponent, commandBuilder, eventBuilder);
  }

  private void buildButtons(Map<String, Item> items,
                            @Nonnull Player playerComponent,
                            @Nonnull UICommandBuilder commandBuilder, @Nonnull UIEventBuilder eventBuilder) {
    commandBuilder.clear("#SubcommandCards");
    commandBuilder.set("#SubcommandSection.Visible", true);
    int rowIndex = 0;
    int cardsInCurrentRow = 0;

    for (Map.Entry<String, Item> entry : items.entrySet()) {
      Item item = entry.getValue();
      if (shop.containItem(item)) continue;
      if (cardsInCurrentRow == 0) {
        commandBuilder.appendInline("#SubcommandCards", "Group { LayoutMode: Left; Anchor: (Bottom: 0); }");
      }

      commandBuilder.append("#SubcommandCards[" + rowIndex + "]", "Pages/ItemsSearchIndex.ui");


      commandBuilder.set("#SubcommandCards[" + rowIndex + "][" + cardsInCurrentRow + "] #ItemIcon.ItemId", entry.getKey());
      commandBuilder.set("#SubcommandCards[" + rowIndex + "][" + cardsInCurrentRow + "] #ItemName.TextSpans", Message.translation(item.getTranslationKey()));
      //commandBuilder.set("#SubcommandCards[" + rowIndex + "][" + cardsInCurrentRow + "] #SubcommandUsage.TextSpans", this.getSimplifiedUsage(item, playerComponent));
      eventBuilder.addEventBinding(CustomUIEventBindingType.Activating, "#SubcommandCards[" + rowIndex + "][" + cardsInCurrentRow + "]", EventData.of("Item", entry.getKey()));
      ++cardsInCurrentRow;
      if (cardsInCurrentRow >= 7) {
        cardsInCurrentRow = 0;
        ++rowIndex;
      }
    }


    //commandBuilder.set("#BackButton.Visible", !this.subcommandBreadcrumb.isEmpty());
  }

  @Override
  public void handleDataEvent(
    @Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @Nonnull SearchGuiData data) {
    super.handleDataEvent(ref, store, data);
    if (data.item != null) {
      this.shop.addProduct(new Product(data.item, BigDecimal.valueOf(1000000), BigDecimal.valueOf(0)));
      this.sendUpdate();
      UICommandBuilder commandBuilder = new UICommandBuilder();
      UIEventBuilder eventBuilder = new UIEventBuilder();
      this.buildList(ref, commandBuilder, eventBuilder, store);
      this.sendUpdate(commandBuilder, eventBuilder, false);
    }
    if (data.searchQuery != null) {
      this.searchQuery = data.searchQuery.trim().toLowerCase();
      UICommandBuilder commandBuilder = new UICommandBuilder();
      UIEventBuilder eventBuilder = new UIEventBuilder();
      this.buildList(ref, commandBuilder, eventBuilder, store);
      this.sendUpdate(commandBuilder, eventBuilder, false);
    }
  }

  private static class SearchResult {
    public static final Comparator<SearchResult> COMPARATOR = Comparator.comparing(o -> o.match);
    private final String name;
    private MatchResult match;

    public SearchResult(String name, MatchResult match) {
      this.name = name;
      this.match = match;
    }
  }
}
